"""Add item_quantity column to products table

Revision ID: 7942cf22b4f9
Revises: 3ec649aafd1a
Create Date: 2024-02-20 21:10:53.532055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7942cf22b4f9'
down_revision: Union[str, None] = '3ec649aafd1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
