"""Add item_quantity column to products table

Revision ID: e981bac40067
Revises: 371b4fabc4c2
Create Date: 2024-02-20 21:04:09.148319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e981bac40067'
down_revision: Union[str, None] = '371b4fabc4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('item_quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'item_quantity')
    # ### end Alembic commands ###
